void main(){


////// ---Way-1----


  var university={
    "name": 'Bangladesh University of Business and Technology',
    "Location":'Mirpur-2 Dhaka',
    "Country":'Bangladesh'
  };
  print(university);
  print(university.keys);
  print(university.values);
  print(university['name']);

////// ---Way-2----

/*var Company=new Map();
  Company['Name']='UniqueCo-IT Solution';
  Company['Country']='Bangladesh';
  Company['Location']='Banani';
  print(Company);
  print(Company.keys);
  print(Company.values);
  print(Company['Name']);*/

////// ---Way-3----

/*var Services =Map<String,dynamic>();
Services["name"]="App Dev";
Services["name1"]="Web Dev";
Services["name2"]="UI/UX Design";
print(Services);
print(Services.keys);
print(Services.values);
print(Services['name']);*/




}
